---
title: "R Decision Making"
output: html_notebook
---

**if , if - else, if - else if - else**

```{r}
x <- c("what","is","truth")
if("Truth" %in% x){
  print("Truth is found")
} else {
  print("Truth is not found")
}
```

**Switch case**

```{r}
v = c(1,3)
x <- switch(length(v),
"First",#length(v),
"second",
"third",
"fourth"
)
print(x)
```


Assignment:: 
Take array of three numbers
Print sum of elements of array based on following conditions
1. Print sum of all elements if 7 is not there in array
2. if 7 is present then sum all elements after 7 and print it
3. if 7 is present in the end then print -1
ex.
a= c(90,7,78) #78
a=c(10,45,34) #89
a=c(7,7,8)    #8
a=c(7,55,10)  #65
a=c(55,10,7)  #-1

```{r}
arr = c(55,10,7)
#arr %in% 7
check_occ = which(arr %in% 7) # array of indexes where 7 is present
#print(length(check_occ))
if( length(check_occ) == 0){
  print(sum(arr))
} else {
    #print(check_occ)
    last_7 = check_occ[length(check_occ)]
    #last_7 = max(check_occ)
    print(last_7)
    
    if(last_7 != length(arr)){
      output = sum(arr[(last_7+1):length(arr)])
      print(output)
    }else {
      print(-1)
    }
}
 
```

```{r}
arr = c(10,7,67)
arr[length(arr)]
```


```{r}
a = c(10,7,7)
match(a,7)
which(a %in% 7)
```

 